[SERVER]
PC_SERVER_IP=192.168.1.126
UDP_PORT=1999
HTTP_PORT=8088
AUTO_DISCOVERY=true

# Delay in seconds to allow Cyclone V FPGA to reconfigure Groovy.rbf before triggering emulator (default: 4)
# Increase to 5 or 6 if your SD card is slow; decrease to 3 if using fast storage.
CORE_LAUNCH_DELAY=5
